apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkxMDAxLmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJaR2hoY21GdWFUcEVhR0Z5WVc1cFFEWT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson